// <auto-generated />
using System;
using Chamados.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chamados.Api.Migrations
{
    [DbContext(typeof(ChamadosDbContext))]
    [Migration("20260724045159_CriaComentario")]
    partial class CriaComentario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chamados.Api.Models.Entities.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("categoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativa = true,
                            Nome = "Hardware"
                        },
                        new
                        {
                            Id = 2L,
                            Ativa = true,
                            Nome = "Software"
                        },
                        new
                        {
                            Id = 3L,
                            Ativa = true,
                            Nome = "Rede"
                        },
                        new
                        {
                            Id = 4L,
                            Ativa = true,
                            Nome = "Acesso"
                        });
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Chamado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<DateTimeOffset?>("FechadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechado_em");

                    b.Property<DateTimeOffset?>("PrazoResolucao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prazo_resolucao");

                    b.Property<DateTimeOffset?>("PrazoResposta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("prazo_resposta");

                    b.Property<long>("PrioridadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_prioridade");

                    b.Property<DateTimeOffset?>("ResolvidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolvido_em");

                    b.Property<string>("SituacaoSlaResolucao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("EmDia")
                        .HasColumnName("situacao_sla_resolucao");

                    b.Property<string>("SituacaoSlaResposta")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("EmDia")
                        .HasColumnName("situacao_sla_resposta");

                    b.Property<long>("SolicitanteId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_solicitante");

                    b.Property<long>("StatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_status");

                    b.Property<long?>("TecnicoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tecnico");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("PrioridadeId");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("chamado", (string)null);
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Comentario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AutorId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_autor");

                    b.Property<long>("ChamadoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_chamado");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Interno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("interno");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("ChamadoId");

                    b.ToTable("comentario", (string)null);
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Historico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("acao");

                    b.Property<long>("AutorId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_autor");

                    b.Property<long>("ChamadoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_chamado");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Detalhe")
                        .HasColumnType("text")
                        .HasColumnName("detalhe");

                    b.Property<long?>("StatusAnteriorId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_status_anterior");

                    b.Property<long?>("StatusNovoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_status_novo");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("StatusAnteriorId");

                    b.HasIndex("StatusNovoId");

                    b.ToTable("historico", (string)null);
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Notificacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChamadoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_chamado");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DestinatarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_destinatario");

                    b.Property<bool>("Lida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("lida");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mensagem");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("DestinatarioId", "Lida");

                    b.ToTable("notificacao", (string)null);
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Perfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("perfil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descricao = "Acesso completo: usuários, configurações de SLA, categorias e prioridades.",
                            Nome = "Administrador"
                        },
                        new
                        {
                            Id = 2L,
                            Descricao = "Atende chamados atribuídos, atualiza status e registra comentários.",
                            Nome = "Técnico"
                        },
                        new
                        {
                            Id = 3L,
                            Descricao = "Abre chamados e acompanha o andamento dos próprios atendimentos.",
                            Nome = "Cliente"
                        });
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Prioridade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Nivel")
                        .HasColumnType("smallint")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("prioridade", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nivel = (short)1,
                            Nome = "Baixa"
                        },
                        new
                        {
                            Id = 2L,
                            Nivel = (short)2,
                            Nome = "Média"
                        },
                        new
                        {
                            Id = 3L,
                            Nivel = (short)3,
                            Nome = "Alta"
                        },
                        new
                        {
                            Id = 4L,
                            Nivel = (short)4,
                            Nome = "Crítica"
                        });
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Sla", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<long>("PrioridadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_prioridade");

                    b.Property<int>("TempoResolucaoMin")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_resolucao_min");

                    b.Property<int>("TempoRespostaMin")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_resposta_min");

                    b.HasKey("Id");

                    b.HasIndex("PrioridadeId")
                        .IsUnique();

                    b.ToTable("sla", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Ativo = true,
                            PrioridadeId = 1L,
                            TempoResolucaoMin = 2880,
                            TempoRespostaMin = 480
                        },
                        new
                        {
                            Id = 2L,
                            Ativo = true,
                            PrioridadeId = 2L,
                            TempoResolucaoMin = 1440,
                            TempoRespostaMin = 240
                        },
                        new
                        {
                            Id = 3L,
                            Ativo = true,
                            PrioridadeId = 3L,
                            TempoResolucaoMin = 480,
                            TempoRespostaMin = 60
                        },
                        new
                        {
                            Id = 4L,
                            Ativo = true,
                            PrioridadeId = 4L,
                            TempoResolucaoMin = 240,
                            TempoRespostaMin = 15
                        });
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Status", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Final")
                        .HasColumnType("boolean")
                        .HasColumnName("final");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome");

                    b.Property<short>("Ordem")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Final = false,
                            Nome = "Aberto",
                            Ordem = (short)1
                        },
                        new
                        {
                            Id = 2L,
                            Final = false,
                            Nome = "Em Atendimento",
                            Ordem = (short)2
                        },
                        new
                        {
                            Id = 3L,
                            Final = false,
                            Nome = "Aguardando Cliente",
                            Ordem = (short)3
                        },
                        new
                        {
                            Id = 4L,
                            Final = true,
                            Nome = "Resolvido",
                            Ordem = (short)4
                        },
                        new
                        {
                            Id = 5L,
                            Final = true,
                            Nome = "Fechado",
                            Ordem = (short)5
                        });
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PerfilId");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Chamado", b =>
                {
                    b.HasOne("Chamados.Api.Models.Entities.Categoria", "Categoria")
                        .WithMany("Chamados")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chamados.Api.Models.Entities.Prioridade", "Prioridade")
                        .WithMany("Chamados")
                        .HasForeignKey("PrioridadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chamados.Api.Models.Entities.Usuario", "Solicitante")
                        .WithMany("ChamadosSolicitados")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chamados.Api.Models.Entities.Status", "Status")
                        .WithMany("Chamados")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chamados.Api.Models.Entities.Usuario", "Tecnico")
                        .WithMany("ChamadosAtendidos")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("Prioridade");

                    b.Navigation("Solicitante");

                    b.Navigation("Status");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Comentario", b =>
                {
                    b.HasOne("Chamados.Api.Models.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chamados.Api.Models.Entities.Chamado", "Chamado")
                        .WithMany()
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Historico", b =>
                {
                    b.HasOne("Chamados.Api.Models.Entities.Usuario", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chamados.Api.Models.Entities.Chamado", "Chamado")
                        .WithMany()
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chamados.Api.Models.Entities.Status", "StatusAnterior")
                        .WithMany()
                        .HasForeignKey("StatusAnteriorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chamados.Api.Models.Entities.Status", "StatusNovo")
                        .WithMany()
                        .HasForeignKey("StatusNovoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Autor");

                    b.Navigation("Chamado");

                    b.Navigation("StatusAnterior");

                    b.Navigation("StatusNovo");
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Notificacao", b =>
                {
                    b.HasOne("Chamados.Api.Models.Entities.Chamado", "Chamado")
                        .WithMany()
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chamados.Api.Models.Entities.Usuario", "Destinatario")
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Destinatario");
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Sla", b =>
                {
                    b.HasOne("Chamados.Api.Models.Entities.Prioridade", "Prioridade")
                        .WithMany()
                        .HasForeignKey("PrioridadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prioridade");
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Usuario", b =>
                {
                    b.HasOne("Chamados.Api.Models.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Categoria", b =>
                {
                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Prioridade", b =>
                {
                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Status", b =>
                {
                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("Chamados.Api.Models.Entities.Usuario", b =>
                {
                    b.Navigation("ChamadosAtendidos");

                    b.Navigation("ChamadosSolicitados");
                });
#pragma warning restore 612, 618
        }
    }
}
